[illumio]
no_pce = true # doesnt try to access the PCE for any data both GET and Update".

[parser]
parserfile = "parser-table.csv"
# noprompt = true
hostnamefile="hostname.csv"
outputfile = "output.csv"

[match]
ignorematch=true
#allempty=true  #overrides label always 
#role = "NoLabel"
app = "NoLabel"
env = "NoLabel"
#loc="NoLabel"

[logging]
#log_only = true # True will make no changes to PCE. Log will reflect what will be updated if set to false.
log_directory = "" # Blank value stores log in same folder where tool is run.
#log_file = "Illumio_Parser.log"
 
